/*
 *   This file was automatically generated by cextract version 1.2.
 *   Manual editing not recommended.
 *
 *   Created: Thu Sep 17 23:54:13 1992
 */
#ifndef __CEXTRACT__
#ifdef __STDC__

extern int main ( void );
extern char * add_signed_string ( const char *s1, const char *s2 );
extern char * add_unsigned_string ( const char *s1, const char *s2 );
extern char * negate_signed_string ( const char *s );
extern char * negate_unsigned_string ( const char *s );
extern char * signed_to_unsigned ( const char *s );
extern char * unsigned_to_signed ( int sign, const char *s );
extern char * normalize_signed ( const char *s );
extern char * subtract_signed_string ( const char *s1, const char *s2 );
extern char * subtract_unsigned_string ( const char *s1, const char *s2 );
extern int compare_signed_string ( const char *s1, const char *s2 );
extern int compare_unsigned_string ( const char *s1, const char *s2 );
extern void print_signed ( const char *s );

#else /* __STDC__ */

extern int main (/* void */);
extern char * add_signed_string (/* const char *s1, const char *s2 */);
extern char * add_unsigned_string (/* const char *s1, const char *s2 */);
extern char * negate_signed_string (/* const char *s */);
extern char * negate_unsigned_string (/* const char *s */);
extern char * signed_to_unsigned (/* const char *s */);
extern char * unsigned_to_signed (/* int sign, const char *s */);
extern char * normalize_signed (/* const char *s */);
extern char * subtract_signed_string (/* const char *s1, const char *s2 */);
extern char * subtract_unsigned_string (/* const char *s1, const char *s2 */);
extern int compare_signed_string (/* const char *s1, const char *s2 */);
extern int compare_unsigned_string (/* const char *s1, const char *s2 */);
extern void print_signed (/* const char *s */);

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
